config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/registration', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :bugs
  resources :users
end

app/models/user.rb
class User < ApplicationRecord
  include ActiveModel::Validations

  # Associations
  has_many :bugs, dependent: :destroy
  has_many :watched_bugs, through: :bug_watchings, source: :bug_id
  has_many :bug_watchings, class_name: "BugWatching",
                           foreign_key: "user_id",
                           dependent: :destroy

  # Ordering
  default_scope -> { order(username: :asc) }

  # Constants
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  # Callbacks
  before_save { self.email = email.downcase }
  
  # Object Attribute Validation
  validates_with UserEmailConfirmationValidator

  attr_accessor :email_confirmation
  validates :email_confirmation, presence: true
   
  # Model Validation
  validates :username, presence: true,
                       length: {maximum: 50},
                       uniqueness: {case_sensitive: false}
  validates :first_name, presence: true, length: {maximum: 50}
  validates :last_name, presence: true, length: {maximum: 50}
  validates :email, presence: true,
                    length: {maximum: 255},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  has_secure_password                  
  validates :password, presence: true,
                       length: {minimum: 8}
  validates :password_confirmation, presence: true
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :verify_admin_user, only: [:index, :destroy]

  def index
    @users = User.all
  end

  def show
    if admin_user?
      puts "redirect to user"
      redirect_to url_for users_path
    else
      puts "redirect to bugs"
      redirect_to url_for bugs_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      if admin_user?
        redirect_to url_for users_path
      else
        flash[:success] = 'You are now registered, please log-in!'
        redirect_to url_for login_path
      end
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:edit_privileges]
      # Case: Privileges
      params[:user][:username] = @user.username
      params[:user][:password] = @user.password_digest
      params[:user][:password_confirmation] = @user.password_digest
      params[:user][:email_confirmation] = @user.email    
    end

    # Update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end
  
  def destroy
    @user.destroy
    redirect_to url_for users_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :first_name,:last_name,
                                   :email, :email_confirmation, :password,
                                   :password_confirmation, :admin,
                                   :developer)
    end

    def find_user
      @user = User.find_by(id: params[:id])
      if @user.nil?
        user_object_not_found
      end

      unless admin_user?
        if !correct_user?(@user)
          permission_error
        end
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form_edit.html.erb
<%= simple_form_for @user do |u| %>
	<%= u.input :email, label:"Email" %>
	<%= u.input :email_confirmation, label:"Confirm your email" %>
	<%= u.input :first_name, label:"First Name" %>
	<%= u.input :last_name, label:"Last Name" %>
	<%= u.input :password, label:"Password (8 character minimum)" %>
	<%= u.input :password_confirmation, label:"Confirm your password" %>
	<%= u.button :submit, name:"edit_main", value:"Save" %>
<% end %>

app/views/users/_form_edit_privileges.html.erb
<%= simple_form_for @user do |u| %>
	<% if @current_user.admin? %>
		<%= u.input :admin, label:"Admin?", default: "false" %>
		<%= u.input :developer, label:"Developer?", default: "false" %>
		<%= u.button :submit, name:"edit_privileges", value:"Change Privileges" %>
	<% end %>
<% end %>

app/views/users/_form_registration.html.erb
<%= simple_form_for @user do |u| %>
	<%= u.input :username, label:"Username" %>
	<%= u.input :email, label:"Email" %>
	<%= u.input :email_confirmation, label:"Confirm your email" %>
	<%= u.input :first_name, label:"First Name" %>
	<%= u.input :last_name, label:"Last Name" %>
	<%= u.input :password, label:"Password (8 character minimum)" %>
	<%= u.input :password_confirmation, label:"Confirm your password" %>
	<%= u.button :submit, value:"Submit" %>
<% end %>

app/views/users/edit.html.erb
<h1>Profile settings for: <span class="username"><%= @user.username %></span></h1>

<% if current_user.admin? %>
    <br>
<% else %>
    <%= link_to 'Back', bugs_path %>
<% end %>

<% if current_user.admin? %>
    <h2>User Privileges</h3>
<% end %>
<%= render 'form_edit_privileges' %>

<% if current_user.admin? %>
    <hr>
    <h2>User Profile</h3>
<% end %>
<%= render 'form_edit' %>

app/views/users/index.html.erb
<h1>User Management</h1>

<%= link_to 'Add a new User', new_user_path %>


	<table class="table">
		<thead>
			<tr>
				<th>ID</th>
				<th>Username</th>
				<th>Email</th>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |u| %>
				<tr>
					<td><%= u.id %></td>
					<td><%= u.username %></td>
					<td><%= u.email %></td>
					<td><%= u.first_name %></td>
					<td><%= u.last_name %></td>
					<td><%= link_to 'edit', edit_user_path(u) %></td>
					<td>
						<%= link_to 'delete', user_path(u),
								method: :delete,
								data: {confirm: "Are you sure?"} %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>

app/views/users/new.html.erb
<h1>New User Registration</h1>

<% if logged_in? && current_user.admin? %>
    <%= link_to 'Back', users_path %>
<% else %>
    <%= link_to 'Back to Login', login_path %>
<% end %>


<%= render "form_registration" %>