config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/registration', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :bugs
  resources :users
end

app/models/bug.rb
class Bug < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :resolver, class_name: 'User', optional: true
  has_many :watchers, through: :bug_watchings, source: :user_id
  has_many :bug_watchings, class_name: "BugWatching",
                           foreign_key: "bug_id",
                           dependent: :destroy

  # Ordering
  default_scope -> { order(created_at: :desc) }

  # Model Validation
  validates :name, presence: true, length: {maximum: 50}
  validates :description, presence: true
  validates :causes, presence: true
  validates :user_id, presence: true
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :find_bug, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user
  
  def index
    if admin_user? || developer_user?
      @bugs = Bug.all
    else
      @bugs = current_user.bugs.all
    end
  end

  def show
  end

  def new
    @bug = Bug.new
  end

  def create
    @bug = current_user.bugs.build(bug_params)
    if @bug.save
      redirect_to url_for Bug
    else
      render 'new'
    end
  end

  def edit
  end
  
  def update
    set_resolver
    if @bug.update(bug_params)
      redirect_to bug_path(@bug)
    else
      render 'edit'
    end
  end
  
  def destroy
    @bug.destroy
    redirect_to url_for Bug
  end

  private
    def bug_params
      params.require(:bug).permit(:name, :error_msg, :description, :causes, :resolved, :resolver_id)
    end

    def find_bug
      if admin_user? || developer_user?
        @bug = Bug.find_by(id: params[:id])
      else
        @bug = current_user.bugs.find_by(id: params[:id])
      end
      
      if @bug.nil?
        user_object_not_found
      end
    end

    def set_resolver
      if params[:bug][:resolved] == '1' && @bug.resolved == false
        verify_developer_user
        params[:bug][:resolver_id] = current_user.id
        puts current_user
      elsif params[:bug][:resolved] == '0' || @bug.resolved == false
        params[:bug][:resolver_id] = nil
      end
    end
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/_form.html.erb
<%= simple_form_for @bug do |f| %>
  <%= f.input :name, label:"Bug" %>
  <%= f.input :error_msg, label:"Error Msg" %>
  <%= f.input :description, label:"Description" %>
  <%= f.input :causes, label:"What causes/caused it?" %>
  <% if @current_user.developer? %>
      <%= f.input :resolved, label:"Resolved?", default: "false" %>
  <% end %>
  <%= f.button :submit, value:"Submit" %>
<% end %>

app/views/bugs/edit.html.erb
<h1>Edit Bug</h1>

<%= link_to 'Back', bug_path(@bug) %>

<%= render 'form' %>

app/views/bugs/index.html.erb
<h1>Bugs</h1>

<div>
	Welcome <span class="username"><%= current_user.first_name %></span>!<br>
	Note: You are currently logged in as <span class="username"><%= current_user.username %></span>.  
	If this is not you, please
	<%= link_to "log out", logout_path, method: :delete %>.<br>
</div>

<div id="bug-list">

	<%= button_to "Report a new Bug", new_bug_path, :method => "get" %>

	<% @bugs.each do |b| %>

		<div class="bug-item">

			<div class="bug-item-name">
				<%= link_to b.name, bug_path(b) %>
			</div>

			<div class="bug-item-desc">
				<p><%= b.description %></p>
			</div>

			<small><%= b.created_at.to_formatted_s(:long)  %> | <span class="username"><%= b.user.username %></span></small><br>

		</div>

	<% end %>

</div>

app/views/bugs/new.html.erb
<h1>Bug Report</h1>

<%= link_to 'Back', bugs_path %>

<%= render "form" %>

app/views/bugs/show.html.erb
<h1>Bug Details</h1>

<%= link_to 'Back', bugs_path %>
<br>

<div class="bug-item">

<%= link_to 'Edit', edit_bug_path(@bug) %> |
<%= link_to 'Delete', bug_path(@bug),
    method: :delete,
		data: {confirm: "Are you sure?"} %>

  <div class="bug-item-name">
    <%= @bug.name %>
  </div>

  <div class="bug-item-desc">
    <div class="bug-item-label">
      desc
    </div>
    <p><%= @bug.description %></p>
  </div>

  <div class="bug-item-error">
    <div class="bug-item-label">
      error msg
    </div>
    <p><%= @bug.error_msg %></p>
  </div>

  <div class="bug-item-causes">
    <div class="bug-item-label">
      causes
    </div>
    <p><%= @bug.causes %></p>
  </div>

  <small>
    Reported by: <span class="username"><%= @bug.user.username %></span>
  </small><br>
  <small>
    Resolved by:
    <% if @bug.resolver %>
      <span class="username"><%= @bug.resolver.username %></span>
    <% else %>
      (n/a)
    <% end %>
  </small><br>
  <small>Created: <%= @bug.created_at.to_formatted_s(:long)   %></small><br>
  <small>Modified: <%= @bug.updated_at.to_formatted_s(:long)   %></small><br>

</div>